[package]
name = "clean-master-privacy"
version = "1.5.0"
edition = "2021"

[dependencies]
# Birbiriyle uyumlu GTK4 ve Libadwaita sürümleri
# Her ikisi de ffi v0.7 / gtk4-sys v0.7 kullanır
gtk4 = "0.7"
libadwaita = "0.5" # 0.4 yerine 0.5 kullanmak çakışmayı çözer
glib = "0.17"

# Diğer sistem bileşenleri
walkdir = "2.3"
notify = "6.0"
dirs = "5.0"
rayon = "1.7"

# Güvenlik ve Analiz
sha2 = "0.10"
humantime = "2.1"

# Async & Runtime
futures = "0.3"
tokio = { version = "1.28", features = ["full"] }
