[package]
name = "clean-master-privacy"
version = "2.5.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
rfd = "0.14"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
