name: Auto-Merge & Branch Cleanup

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  check_run:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' || contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Auto-merge PRs
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "" # Boş bırakılırsa tüm uygun PR'ları birleştirir
          MERGE_METHOD: "squash" # Geçmişi temiz tutmak için squash kullanıyoruz
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"

  cleanup:
    runs-on: ubuntu-latest
    needs: automerge
    if: github.event.pull_request.merged == true
    steps:
      - name: Delete merged branch
        uses: SML_P/delete-merged-branches@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
